### ISSUE TITLE
Archlinux PKGBUILD fails

### ISSUE THREAD

**Issue by godofgrunts** [Aaron-SP/bds#2] opened 2018-06-01 01:11 UTC
==> Starting build()...
make: freetype-config: Command not found
g++ -I/usr/include/mgl/file -I/usr/include/mgl/geom -I/usr/include/mgl/math -I/usr/include/mgl/platform -I/usr/include/mgl/renderer -I/usr/include/mgl/scene -I/usr/include/mgl/sound -Isource  -Itest  -s -std=c++14 -Wall -O3 -fomit-frame-pointer -freciprocal-math -ffast-math -static-libgcc -static-libstdc++   -march=native -DGLEW_STATIC /usr/include/mgl/platform/min/glew.cpp test/test.cpp -o bin/tests -lX11 -lGL -lfreetype -pthread -lopenal -lvorbisfile 2> "test.txt"
make: *** [makefile:73: tests] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

This is caused by freetype-config needing to be replaced by "pkg-config freetype2" I think.  (https://bugs.archlinux.org/task/58447)

MGL is broken because of this as well.

**Comment by Aaron-SP** [comment] 2018-06-02 03:59
Do you have freetype2 installed? If this is correct it seems like a fairly new problem. 

Verify that you have the needed dependencies installed first... 

`pacman -S freetype2 xorg-server xorg-server-devel openal libvorbis`

And then retry the build.

The PKGBUILD lists the dependencies but I have always had problems with makepkg actually installing any of them. `makepkg --syncdeps` may be needed. I will have to revert my machine to Arch to test.

**Comment by Aaron-SP** [comment] 2018-06-02 04:25
After looking at this, it seems the freetype2 people finally removed the freetype-config script, but it shouldn't be a problem since pkg-config works almost the same way.

I patched MGL and BDS with the `pkg-config freetype2 --cflags` command to retrieve the freetype directory. 

I tested it on CYGWIN without issue so I pushed it without testing on Arch. I will be testing on Ubuntu shortly to see if any issue arises.

Pull the latest MGL and BDS and verify the issue is resolved for you.

**Comment by Aaron-SP** [comment] 2018-06-02 04:45
No problems on Ubuntu 14.04. I updated the PKGBUILD's for **mgl** and **bds** so you can reinstall the latest version. It looks like it won't cause any trouble.

I decided not to revert my test machine to Arch just yet, so let me know if you have any issues with it.

**Comment by Aaron-SP** [comment] 2018-06-08 19:36
I am closing this issue. If you still have problems, create a new issue.

**Closed as completed by Aaron-SP** 2018-06-08 19:36 UTC
Labels: bug

**Comment by godofgrunts** [comment] 2018-06-08 20:42
I'm sorry. This got away from me. I'll confirm tonight.
